# Generated by Django 5.0.6 on 2026-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant'), ('ADMIN', 'Administrateur')], default='ETUDIANT', max_length=20, verbose_name='Rôle'),
        ),
    ]
