# Generated by Django 5.2.7 on 2026-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ENSEIGNANT', 'Enseignant'), ('ADMIN', 'Administrateur'), ('ADMIN_SYS', 'Administrateur systeme')], default='ETUDIANT', max_length=20, verbose_name='Role'),
        ),
    ]
