# Generated by Django 5.2.7 on 2026-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_department_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emsi_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID EMSI'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ELEVE', 'Eleve'), ('ENSEIGNANT', 'Enseignant'), ('PROFESSEUR', 'Professeur')], default='ELEVE', max_length=20, verbose_name='Role'),
        ),
    ]
