# Generated by Django 5.0.6 on 2026-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, help_text='Liste des équipements disponibles (ex: projecteur, tableau, wifi)', verbose_name='Équipements'),
        ),
    ]
