# Generated by Django 5.2.7 on 2026-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, help_text='Liste des equipements disponibles (ex: projecteur, tableau, wifi)', verbose_name='Equipements'),
        ),
    ]
