# Generated by Django 5.2.7 on 2026-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'code']},
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default='EMSI', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('CLASSROOM', 'Salle de cours'), ('LAB', 'Laboratoire informatique'), ('CONFERENCE', 'Salle de conference')], default='CLASSROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
