# Generated by Django 5.2.7 on 2026-04-27 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_user'),
        ('rooms', '0003_alter_room_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmee'), ('ANNULEE', 'Annulee')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date'], name='bookings_bo_room_id_f1d72e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'date'], name='bookings_bo_user_id_4a9385_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('room', 'date', 'start_time'), name='unique_room_date_start_time'),
        ),
    ]
